name: pm21-rabbit
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pip=23.1.2
  - snakemake-minimal=7.26.0

  - numpy=1.24.3
  - pandas=2.0.2

  - matplotlib=3.7.1
  - seaborn=0.12.2

  - scipy=1.10.1
  - scikit-image=0.20.0
  - scikit-learn=1.2.2

  - pytables=3.8.0

  - imageio=2.28.1
  - imageio-ffmpeg=0.4.8

  - pymc=5.3.0
  - python-graphviz=0.20.1

  - nbgrader=0.8.2
  - jupyterhub=4.0.1
  - nbdev=2.2.10
  - nbconvert=7.4.0
  - jupyter_server=1.23.4

  - requests=2.31.0

  - biopython=1.81
  - scanpy=1.9.3

  - pip:
      - adskalman==0.3.11
      - dabest==2023.2.14
      - figurefirst==0.0.6
      - ultralytics==8.1.9
